---
- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ntp
    - python2-cryptography
    - setools-console
    - policycoreutils-python

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Enable ntpd
  systemd:
    name: ntpd
    enabled: true
    state: restarted

- name: "Add my own IP to /etc/hosts instead localhost"
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
    replace: "{{ ansible_host }} {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}"

- name: "Add {{ master_hostname }}.{{ domain }} IP to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "{{ master_ip }} {{ master_hostname }}.{{ domain }} {{ master_hostname }}"
    state: present

- name: "Add {{ slave_hostname }}.{{ domain }} IP to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "{{ slave_ip }} {{ slave_hostname }}.{{ domain }} {{ slave_hostname }}"
    state: present
...